name: Backup

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron:  0 */2 * * *

env:
  FILES_DIR: "."
  SITE_URL: https://mohu.rocks
  UA: Mozilla/5.0 (rv:79.0) Gecko/20100101 Firefox/79.0
  CONCURRENCY: 40

jobs:
  backup:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow_fail || false }}

    strategy:
      matrix:
        backup_type: [user, article, video]
        include:
          - { backup_type: topic, allow_fail: true }
          - { backup_type: question, start_id: 10001, allow_fail: true }
          - { backup_type: question, start_id: 5001, end_id: 10000 }
          - { backup_type: question, start_id: 1, end_id: 5000 }
      fail-fast: false

    env:
      BACKUP_TYPE: ${{ matrix.backup_type }}
      START_ID: ${{ matrix.start_id }}
      END_ID: ${{ matrix.end_id }}

    steps:
    # - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 10
          path: ${{ env.FILES_DIR }}

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: git config --global user.email bot@example.com
      - run: git config --global user.name bot

      - run: npm install

      - name: main
        run: npm run backup;

      - run: mv imo img || true

      - name: commit
        run: |
          cd $FILES_DIR;
          git pull;
          git add .;
          git commit -m "$(date -uI)";
          git pull;
          git push;

