name: Upload

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron:  0 */2 * * *

jobs:
  ipfs:
    name: Upload to IPFS
    runs-on: ubuntu-latest
    env:
      OUTPUT: IPFS_HASH
      IPFS_BIN: ./node_modules/.bin/jsipfs
      API: https://ipfs.infura.io:5001/
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: git config --global user.email bot@example.com
      - run: git config --global user.name bot

      - name: Cleanup
        run: rm $OUTPUT

      - run: npm i ipfs
      - run: $IPFS_BIN init -e
      - name: ipfs add
        run: |
          ls -I node_modules -I package.json -I package-lock.json -I index.js | xargs -I {} sh -c \
            "echo {}; \
            $IPFS_BIN add --progress=false -r {} | tail -1 >> $OUTPUT; \
            $IPFS_BIN --api $API add --progress=false -r {}"

      - name: Final IPFS CID
        run: $IPFS_BIN add -Q -r . >> $OUTPUT

      - name: commit ipfs cid
        run: |
          git pull;
          git add $OUTPUT;
          git commit -m "ipfs hash";
          git pull;
          git push;

      - name: Sync
        run: |
          CID=$(tail -1 $OUTPUT);
          echo $CID;

          for i in {1..50}
          do
            $IPFS_BIN --api $API pin add $CID;
          done
