name: Upload

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron:  0 */2 * * *

jobs:
  npm:
    name: Upload to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set package version
        run: npm version "1.0.0-$(git rev-parse --short HEAD)" --no-git-tag
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # 9a4f**********

  ipfs:
    name: Upload to IPFS
    runs-on: ubuntu-latest
    env:
      OUTPUT: IPFS_HASH
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: git config --global user.email bot@example.com
      - run: git config --global user.name bot

      - name: Cleanup
        run: rm index.js package.*

      - name: ipfs add
        run: |
          npx ipfs --api https://ipfs.infura.io:5001/ add --progress=false -r . \
            | tee >(tail -1 | cut -d' ' -f2 > $OUTPUT)

      - name: commit ipfs cid
        run: |
          git add $OUTPUT;
          git commit -m "ipfs://$(cat $OUTPUT)";
          git push;
