name: Upload

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron:  0 */2 * * *

jobs:
  npm:
    name: Upload to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          registry-url: https://skimdb.npmjs.com/registry
          node-version: 12
      - name: Set package version
        run: npm version "1.0.0-$(git rev-parse --short HEAD)" --no-git-tag
      - run: npm remove wecenter-backup-helper
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # e866**********

  ipfs:
    name: Upload to IPFS
    runs-on: ubuntu-latest
    env:
      OUTPUT: IPFS_HASH
      IPFS_BIN: ./node_modules/.bin/jsipfs
      API: https://ipfs.infura.io:5001/
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: git config --global user.email bot@example.com
      - run: git config --global user.name bot

      - name: Cleanup
        run: rm index.js package.* $OUTPUT

      - run: npm i ipfs
      - name: ipfs add
        run: |
          ls | xargs -I {} sh -c \
            "echo {}; $IPFS_BIN --api $API add --progress=false -r {} | tee /dev/tty | tail -1 >> $OUTPUT"

      - name: commit ipfs cid
        run: |
          git add $OUTPUT;
          git commit -m "ipfs hash";
          git push;
